version: "3.8"

services:
  monorepo_prod:
    container_name: nestjs-remix-monorepo-prod
    image: thiez64/nestjs-remix-monorepo:production
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV
      - DATABASE_URL
    depends_on:
      - redis_prod
    networks:
      - remix_network

  redis_prod:
    image: redis:latest
    container_name: remix-nestjs-monorepo-redis_prod-1
    restart: always
    command: ["redis-server"]
    volumes:
      - /dev/volumes/nestjs-remix/production/sessions/:/data
    networks:
      - remix_network

networks:
  remix_network:
    driver: bridge
